version: "3.8"

networks:
  cockroachnetwork:
    name: cockroachnetwork
    driver: bridge

services:
  mysqlcockroach:
    image: mysql:latest
    container_name: mysqlcockroach
    ports:
      - target: 3306 # port di container
        published: 3306 # port di local
        protocol: tcp
        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - cockroachnetwork
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # dir local : dir container

  cockroachapp :
    build: .
    container_name: cockroachapp
    ports:
      - target: 5000 # port di container
        published: 5000 # port di local
    networks:
      - cockroachnetwork
    depends_on:
      - mysqlcockroach

