version: "3.8"

networks:
  cockroach-network:
    name: cockroach-network
    driver: bridge

services:
  mysql-cockroach:
    image: mysql:latest
    container_name: mysql-cockroach
#    ports:
#      - target: 3306 # port di container
#        published: 3307 # port di local
#        protocol: tcp
#        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - cockroach-network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # dir local : dir container

  cockroach-app :
    build: .
    container_name: cockroach-app
    ports:
      - target: 3000 # port di container
        published: 3000 # port di local
    networks:
      - cockroach-network
    depends_on:
      - mysql-cockroach

